### ISSUE TITLE
How to capture screenshots in allure reports

### ISSUE THREAD

**Issue by neerjain** [korobochka/cucumberjs-allure2-reporter#5]
I am using this reporter and successfully able to generate reports but I am not able to attach the screenshots in this report.

In my hooks. js, I have created a function to take screenshot on failure in After but still screenshot is not captured in report.

**hooks.js :**

const { BeforeAll, After, Status } = require("cucumber");
    After(function(scenario) {
      
      if (scenario.result.status === Status.FAILED) {
        const attach = this.attach; // cucumber's world object has attach function which should be used
        return browser.takeScreenshot().then(function(png) {
          const decodedImage = new Buffer(png, "base64");
          return attach(decodedImage, "image/png");
        });
      }
    });

**Versions**
Node - 8.11.3
CucumberJs - 4.2.1
Protractor-Cucumber-Framework - 6.1.1

Please help me on this.

**Comment by neerjain** [comment]
Got this working , so closing the issue

**Comment by korobochka** [comment]
@neerjain Can you please share how you got it working in case someone has a similar problem?
